[workspace]
resolver = "2"
members = [
    "crates/ironhold_core",
    "crates/ironhold_native",
    "crates/ironhold_web",
    "crates/ironhold_cli",
]

[workspace.dependencies]
bevy = { version = "0.18.0", features = ["serialize", "wav", "vorbis", "mp3", "jpeg"] }
serde = { version = "1.0", features = ["derive"] }
ron = "0.11"
bevy_common_assets = { git = "https://github.com/NiklasEi/bevy_common_assets", rev = "ae3243defb5c07170c1ece647061f4117cf5f97e" }
bevy_framepace = "0.21"
wasm-bindgen = "0.2"

[profile.release]
opt-level = "s"   # optimise for binary size; important for WASM GitHub Pages limit

[profile.test]
debug = true
opt-level = 3
debug-assertions = true
overflow-checks = true
split-debuginfo = "packed" # Extracts symbols into a separate .dwp file

[profile.test.package."*"]
opt-level = 3       # Match release performance for Bevy engine code

[profile.dev]
opt-level = 3       # Match release performance for local code
debug = true        # Retain full debugging info (symbols, line tables)
debug-assertions = true
overflow-checks = true # Keep panic safety features active for dev
split-debuginfo = "packed" # Extracts symbols into a separate .dwp file

[profile.dev.package."*"]
opt-level = 3       # Match release performance for Bevy engine code