[workspace]
resolver = "2"
members = [
    "crates/ironhold_core",
    "crates/ironhold_native",
    "crates/ironhold_web",
    "crates/ironhold_cli",
]

[workspace.dependencies]
bevy = { version = "0.18.0", features = ["serialize", "wav", "vorbis", "mp3", "jpeg"] }
serde = { version = "1.0", features = ["derive"] }
ron = "0.11"
bevy_common_assets = { git = "https://github.com/NiklasEi/bevy_common_assets", rev = "ae3243defb5c07170c1ece647061f4117cf5f97e" }
bevy_framepace = "0.21"
wasm-bindgen = "0.2"

[profile.release]
opt-level = "s"   # optimise for binary size; important for WASM GitHub Pages limit

[profile.test]
debug = true
opt-level = 0
debug-assertions = true
overflow-checks = true
