[package]
name = "ironhold_native"
version = "0.1.0"
edition = "2021"
description = "The runtime native build of Ironhold"
repository = "https://github.com/frankvangeest/ironhold-lib"
license = "MIT OR Apache-2.0"
authors = ["Frank van Geest"]

[dependencies]
ironhold_core = { path = "../ironhold_core" }
bevy = { workspace = true }
[features]
inspector = ["ironhold_core/inspector"]
