[package]
name = "ironhold_web"
version = "0.1.0"
edition = "2021"
description = "The runtime web build of Ironhold"
repository = "https://github.com/frankvangeest/ironhold-lib"
license = "MIT OR Apache-2.0"
authors = ["Frank van Geest"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ironhold_core = { path = "../ironhold_core" }
bevy = { workspace = true }
wasm-bindgen = { workspace = true }

# For the DebugState in the DOM and browser tests
[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3", features = ["Window", "Location", "UrlSearchParams"] }

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[features]
inspector = ["ironhold_core/inspector"]
webgpu = ["bevy/webgpu"]
