[package]
name = "ironhold_web"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ironhold_core = { path = "../ironhold_core" }
bevy = { workspace = true }
wasm-bindgen = { workspace = true }

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[features]
inspector = ["ironhold_core/inspector"]

[profile.test]
debug = true
opt-level = 0
debug-assertions = true
overflow-checks = true
