[package]
name = "ironhold_core"
version = "0.1.0"
edition = "2021"
description = "The core runtime of Ironhold"
repository = "https://github.com/frankvangeest/ironhold-lib"
license = "MIT OR Apache-2.0"
authors = ["Frank van Geest"]

[dependencies]
bevy = { workspace = true, features = ["debug"] }
serde = { workspace = true }
ron = { workspace = true }
bevy_common_assets = { workspace = true, features = ["ron"] }
bevy_inspector_egui = { package = "bevy-inspector-egui", version = "0.36", optional = true }
bevy_rapier3d = { version = "0.33", features = ["enhanced-determinism", "serde-serialize"] }
bevy_mesh = "0.18"
futures-lite = "2.3"

# For the DebugState in the DOM and browser tests
[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3", features = ["Window", "Document", "Element"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
bevy_framepace = { workspace = true }

[features]
inspector = ["dep:bevy_inspector_egui"]
