[package]
name = "ironhold_core"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
serde = { workspace = true }
ron = { workspace = true }
bevy_common_assets = { workspace = true, features = ["ron"] }
bevy_inspector_egui = { package = "bevy-inspector-egui", version = "0.36", optional = true }
bevy_rapier3d = { version = "0.33", features = ["enhanced-determinism", "serde-serialize"] }
bevy_mesh = "0.18"
futures-lite = "2.3"

[features]
inspector = ["dep:bevy_inspector_egui"]
